# Package the official prebuilt Linux release instead of compiling the nixpkgs
# source package (which pulls rustPlatform plus a vendored zig_0_16 libghostty-vt
# dependency). Upstream ships a statically linked x86_64 ELF — no PT_INTERP and
# no DT_NEEDED entries — so there is nothing to autoPatchelf and the binary runs
# directly inside the build sandbox.
#
# Completions and the agent skill are generated by running the binary at build
# time, matching what nixpkgs' herdr package installs via installAgentSkills.
#
# `herdr update` cannot work against the immutable store; upgrades go through
# `just update-overlay herdr`.
{
  lib,
  stdenvNoCC,
  fetchurl,
  installShellFiles,
  versionCheckHook,
}:
let
  versions = builtins.fromJSON (builtins.readFile ./versions.json);
  pname = "herdr";
  version = versions.version;
in
stdenvNoCC.mkDerivation (finalAttrs: {
  inherit pname version;

  # Upstream publishes a bare binary rather than an archive, so fetchurl drops
  # it at $src and the default unpack phase would fail; skip it below.
  src = fetchurl {
    url = "https://github.com/herdrdev/herdr/releases/download/v${finalAttrs.version}/herdr-linux-x86_64";
    sha256 = versions.sha256;
  };

  nativeBuildInputs = [
    installShellFiles
    versionCheckHook
  ];

  dontUnpack = true;
  dontBuild = true;
  doInstallCheck = true;

  installPhase = ''
    runHook preInstall

    install -Dm755 $src $out/bin/herdr

    ${lib.optionalString (stdenvNoCC.buildPlatform.canExecute stdenvNoCC.hostPlatform) ''
      $out/bin/herdr completion bash > herdr.bash
      $out/bin/herdr completion fish > herdr.fish
      $out/bin/herdr completion zsh > herdr.zsh
      installShellCompletion --cmd herdr \
        --bash herdr.bash \
        --fish herdr.fish \
        --zsh herdr.zsh

      # Upstream keeps the skill at skills/herdr/SKILL.md; nixpkgs'
      # installAgentSkills hook lands it in share/skills/herdr/herdr. The
      # binary prints the same document with --skill.
      $out/bin/herdr --skill > herdr.skill.md
      install -Dm644 herdr.skill.md \
        $out/share/skills/herdr/herdr/SKILL.md
    ''}

    runHook postInstall
  '';

  meta = {
    description = "Agent multiplexer that lives in your terminal";
    homepage = "https://herdr.dev";
    changelog = "https://github.com/herdrdev/herdr/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.asl20;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
    platforms = [ "x86_64-linux" ];
    maintainers = with lib.maintainers; [ ];
    mainProgram = "herdr";
  };
})
